# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HopeWL' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'Moya'
pod 'KeychainSwift', '~> 19.0'
pod 'AZTabBar'
pod 'Kingfisher'
pod 'IQKeyboardManagerSwift'
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'Firebase/Database'

  # Pods for HopeWL

end
